version: "3"


services:

    rabbitmq:
        build: "./rabbitmq"
        ports:
            - 15672:15672
            - 5672:5672
            - 5671:5671
        
    json-data-server:
        build: "./json-data-server"
        ports:
            - 3001:3001

    text-data-server:
        build: "./text-data-server"
        ports:
            - 3002:3002

    carrental-service:
        build: "./carrental-service"
        ports:
            - 3003:3003
        depends_on: 
            - "rabbitmq"
        command: ["node", "server.js"]
        links:
            - "text-data-server"
            - "json-data-server"

    rating-service:
        build: "./rating-service"
        ports:
            - 3004:3004

